---
- name: Wait for SSH connection
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure SSH port open
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

- name: Install Docker and ACL
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Install ACL
      yum:
        name: acl
        update_cache: yes
        state: present

- name: Create new Linux user
  hosts: all
  become: true
  vars_files:
    - project-vars.yaml
  tasks:
    - name: Create new Linux user
      user:
        name: "{{new_user_name}}"
        groups: adm,docker

- name: Install Docker-Compose
  hosts: all
  vars_files:
    - project-vars.yaml
  become: true
  become_user: "{{new_user_name}}"
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install Docker-Compose plugins
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{remote_arch.stdout}}
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x

- name: Start Docker
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started

- name: Start Docker containers
  hosts: all
  become: true
  become_user: "{{new_user_name}}"
  vars_files:
    - project-vars.yaml
  tasks:
    - name: Copy Docker-Compose
      copy:
        src: docker-compose-full.yaml
        dest: /home/{{new_user_name}}/docker-compose.yaml
    - name: Docker login
      docker_login:
        username: "{{docker_username}}"
        password: "{{docker_password}}"
    - name: Start containers from compose
      community.docker.docker_compose_v2:
        project_src: /home/{{new_user_name}}
      register: run_compose_result
    - debug: msg="{{run_compose_result.stderr_lines}}"