---
- name: Install Node & NPM
  hosts: ec2_ubuntu
  become: true
  tasks:
    - name: Update apt repo & cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install NodeJs & NPM
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new Linux user for the app
  hosts: ec2_ubuntu
  become: true
  vars_files:
    project-vars.yaml
  tasks:
    - name: Create Linux user
      user:
        name: "{{linux_user_name}}"
        comment: NodeJS app user
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}

- name: Deploy NodeJs app
  hosts: ec2_ubuntu
  become: true
  vars_files:
    project-vars.yaml
  become_user: "{{linux_user_name}}"
  tasks:
    - name: Unpack the NodeJS file
      unarchive:
        src: /home/imre-bodnar/nodejs-app/nodejs-app-{{app_version}}.tgz
        dest: "{{base_folder}}"
    - name: Install dependencies
      npm:
        path: "{{base_folder}}/package"
    - name: Start the app
      command:
        chdir: "{{base_folder}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensuring the app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
