networks:
  raid_network:
    name: raid-network
    driver: bridge

services:
  raid.webapi:
    image: bodnarimredocker/raid-webapi
    container_name: Raid.WebApi
    networks:
      - raid_network

  raid.webui:
    image: bodnarimredocker/raid-webui
    container_name: Raid.WebUi
    depends_on:
      - raid.webapi
    networks:
      - raid_network
